package:
  name: pytorch-speedup
  version: 0.1

source:
  path: .
  #git_rev:
  #git_url:

requirements:
  build:
    - python
    - pip
    - setuptools
    #- cudnn 7.6.5 cuda10.2_0
    - numpy 
    - ninja 
    - pyyaml 
    - mkl 
    - mkl-include 
    - setuptools
    - cmake 
    - cffi 
    - typing_extensions 
    - future 
    - six 
    - requests 
    - dataclasses 
    - ipython 
    - pkg-config
    - magma-cuda113

  run:
    - python
    - pip
    #- cudnn 7.6.5 cuda10.2_0
    - magma-cuda113
    - mkl
    - cffi
    - ninja
    - numpy
    - typing_extensions

test:
  imports:
    - torch
    #- torchvision

about:
  home:
